// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvt5BcvCk1ZJVlP_FVeGxWWUf4mybbO1I',
    appId: '1:202294047450:web:be6136a44fd467609aebe3',
    messagingSenderId: '202294047450',
    projectId: 'productau',
    authDomain: 'productau.firebaseapp.com',
    storageBucket: 'productau.firebasestorage.app',
    measurementId: 'G-T8W36L5T4Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUQKsiIVLScrcnQllscxNcx9-mcoE4j-s',
    appId: '1:202294047450:android:ae79ee77244b87ae9aebe3',
    messagingSenderId: '202294047450',
    projectId: 'productau',
    storageBucket: 'productau.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsNJ46jH1mSLFz5TDWStyrYY938lWepiA',
    appId: '1:202294047450:ios:c0f3a088d853c40e9aebe3',
    messagingSenderId: '202294047450',
    projectId: 'productau',
    storageBucket: 'productau.firebasestorage.app',
    iosBundleId: 'com.example.productAu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsNJ46jH1mSLFz5TDWStyrYY938lWepiA',
    appId: '1:202294047450:ios:c0f3a088d853c40e9aebe3',
    messagingSenderId: '202294047450',
    projectId: 'productau',
    storageBucket: 'productau.firebasestorage.app',
    iosBundleId: 'com.example.productAu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvt5BcvCk1ZJVlP_FVeGxWWUf4mybbO1I',
    appId: '1:202294047450:web:bf0f59c5118b57769aebe3',
    messagingSenderId: '202294047450',
    projectId: 'productau',
    authDomain: 'productau.firebaseapp.com',
    storageBucket: 'productau.firebasestorage.app',
    measurementId: 'G-40YN05NF7C',
  );
}
